language: php

php:
    - 5.3
    - 5.5
    - 7.0

env:
    - WP_VERSION=latest WP_MULTISITE=0

matrix:
  fast_finish: true
  allow_failures:
    - env: WP_VERSION=3.8 WP_MULTISITE=0
      php: 7.0

before_script:
    - bash tests/bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script:
  - if [[ $TRAVIS_PHP_VERSION = '7.0' && $WP_VERSION = 'latest' && $WP_MULTISITE = '0' ]]; then phpunit --coverage-clover=coverage.clover; else phpunit; fi

after_script:
    - if [[ $TRAVIS_PHP_VERSION = '7.0' && $WP_VERSION = 'latest' && $WP_MULTISITE = '0' ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
    - if [[ $TRAVIS_PHP_VERSION = '7.0' && $WP_VERSION = 'latest' && $WP_MULTISITE = '0' ]]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
branches:
    only:
        - master